RUNS = {
    # "EleutherAI/pythia-70m": "s8qh8azh",
    # "EleutherAI/pythia-160m": "78zt5b5f",
    # "EleutherAI/pythia-410m": "dkte7uzy",
    # "EleutherAI/pythia-1.4b": "52xf5zjn",
    # "EleutherAI/pythia-2.8b": "91dqlyy8",
    # "tiiuae/falcon-7b": "jcptmzek",
    # "gpt2-large": "r0u0bjcz",
    # "gpt2-medium": "47z3cdgr",
    # "gpt2": "2lhuc940",
    # "EleutherAI/gpt-j-6b": "81vkf85b",
    "meta-llama/Llama-2-7b-hf": "p16wh1qg",
    "gpt2-xl": "xozj5ub1",
    "mistralai/Mistral-7B-v0.1": "4hcvqiwu",
    "google/gemma-2b": "y2opgjol",
    "microsoft/phi-2": "v7711eze",
}


sg_mapping = {
    "fgd_hierarchy.json": "Long-Distance Dependencies",
    "subordination_src-src.json": "Gross Syntactic State",
    "reflexive_src_fem.json": "Licensing",
    "npz_obj_mod.json": "Garden-Path Effects",
    "npi_src_any.json": "Licensing",
    "reflexive_prep_fem.json": "Licensing",
    "fgd-embed3.json": "Long-Distance Dependencies",
    "subordination.json": "Gross Syntactic State",
    "reflexive_prep_masc.json": "Licensing",
    "cleft_modifier.json": "Long-Distance Dependencies",
    "fgd_subject.json": "Long-Distance Dependencies",
    "mvrr.json": "Garden-Path Effects",
    "npi_src_ever.json": "Licensing",
    "npz_ambig.json": "Garden-Path Effects",
    "cleft.json": "Long-Distance Dependencies",
    "npi_orc_ever.json": "Licensing",
    "mvrr_mod.json": "Garden-Path Effects",
    "center_embed.json": "Center Embedding",
    "fgd-embed4.json": "Long-Distance Dependencies",
    "reflexive_src_masc.json": "Licensing",
    "subordination_pp-pp.json": "Gross Syntactic State",
    "subordination_orc-orc.json": "Gross Syntactic State",
    "number_orc.json": "Agreement",
    "npz_obj.json": "Garden-Path Effects",
    "reflexive_orc_masc.json": "Licensing",
    "number_prep.json": "Agreement",
    "fgd_object.json": "Long-Distance Dependencies",
    "npz_ambig_mod.json": "Garden-Path Effects",
    "center_embed_mod.json": "Center Embedding",
    "number_src.json": "Agreement",
    "reflexive_orc_fem.json": "Licensing",
    "fgd_pp.json": "Long-Distance Dependencies",
    "npi_orc_any.json": "Licensing",
}

sg_num_items = {
    "fgd_hierarchy.json": 24,
    "subordination_src-src.json": 23,
    "reflexive_src_fem.json": 19,
    "npz_obj_mod.json": 24,
    "npi_src_any.json": 38,
    "reflexive_prep_fem.json": 19,
    "fgd-embed3.json": 21,
    "subordination.json": 23,
    "reflexive_prep_masc.json": 19,
    "cleft_modifier.json": 40,
    "fgd_subject.json": 24,
    "mvrr.json": 28,
    "npi_src_ever.json": 38,
    "npz_ambig.json": 24,
    "cleft.json": 40,
    "npi_orc_ever.json": 38,
    "mvrr_mod.json": 28,
    "nn-nv-rpl.json": 1,
    "center_embed.json": 28,
    "fgd-embed4.json": 21,
    "reflexive_src_masc.json": 19,
    "subordination_pp-pp.json": 23,
    "subordination_orc-orc.json": 23,
    "number_orc.json": 19,
    "npz_obj.json": 24,
    "reflexive_orc_masc.json": 19,
    "number_prep.json": 19,
    "fgd_object.json": 24,
    "npz_ambig_mod.json": 24,
    "center_embed_mod.json": 28,
    "number_src.json": 19,
    "reflexive_orc_fem.json": 19,
    "fgd_pp.json": 24,
    "npi_orc_any.json": 38,
}
